language: pt
pipeline: "supervised_embeddings"
policies:
  - name: "KerasPolicy"
    featurizer:
    - name: MaxHistoryTrackerFeaturizer
      max_history: 5
      state_featurizer:
        - name: BinarySingleStateFeaturizer
    epochs: 400
    batch_size: 50
    validation_split: 0.2
  - name: "MemoizationPolicy"
    max_history: 5