intents:
- cumprimentar
- obter_notas
- enviar_email_coordenador
- enviar_email_professor
- mandar_corpo_email
- mandar_materia
- obter_media
- data_prova

entities:
- corpo_email_coordenador

slots:
  corpo_email_coordenador:
    type: text
  res_corpo_email:
    type: text
  corpo_email_professor:
    type: text
  disciplina:
    type: text
  data_prova:
    type: text

templates:
  utter_cumprimentar:
  - text: "{'message': 'Olá! Me chamo Túlio, em que posso lhe ajudar? Atualmente posso lhe dar suporte em Enviar email para a coordenação. Enviar email para um professor. Calcular média. Data das provas.','status': 0,'action': '','contents': {}}"

  utter_pega_corpo_email:
  - text: "{'message': 'Muito bem. Poderia me falar, resumidamente, qual seria o conteúdo do email?','status': 0,'action': '','contents': {}}"

  utter_email_enviado:
  - text: "{res_corpo_email}"

  utter_media_disciplina:
  - text: "{disciplina}"

  utter_pega_materia:
    - text: "{'message': 'Ok. Para qual matéria deseja enviar o email?','status': 0,'action': '','contents': {}}"

  utter_pega_materia_media:
    - text: "{'message': 'Ok. Qual matéria você deseja calcular a média?','status': 0,'action': '','contents': {}}"

  utter_data_prova:
    - text: "{data_prova}"

actions:
- utter_cumprimentar
- utter_pega_corpo_email
- action_monta_res_coordenador
- utter_email_enviado
- utter_pega_materia
- action_monta_res_professor
- utter_pega_materia_media
- utter_media_disciplina
- action_media_disciplina
- utter_data_prova
- action_data_prova
